// Mocks generated by Mockito 5.4.6 from annotations
// in talowa/test/services/messaging/backup_recovery_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:talowa/services/auth_service.dart' as _i2;
import 'package:talowa/services/messaging/backup_scheduler_service.dart' as _i9;
import 'package:talowa/services/messaging/data_backup_service.dart' as _i3;
import 'package:talowa/services/messaging/data_migration_service.dart' as _i8;
import 'package:talowa/services/messaging/disaster_recovery_service.dart'
    as _i6;
import 'package:talowa/services/messaging/message_retention_service.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [DataBackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataBackupService extends _i1.Mock implements _i3.DataBackupService {
  MockDataBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> createFullBackup({
    bool? includeMessages = true,
    bool? includeCallHistory = true,
    bool? includeConversations = true,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFullBackup,
          [],
          {
            #includeMessages: includeMessages,
            #includeCallHistory: includeCallHistory,
            #includeConversations: includeConversations,
            #metadata: metadata,
          },
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #createFullBackup,
            [],
            {
              #includeMessages: includeMessages,
              #includeCallHistory: includeCallHistory,
              #includeConversations: includeConversations,
              #metadata: metadata,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> exportUserData({
    bool? includeMessages = true,
    bool? includeCallHistory = true,
    bool? includeConversations = true,
    String? format = 'json',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportUserData,
          [],
          {
            #includeMessages: includeMessages,
            #includeCallHistory: includeCallHistory,
            #includeConversations: includeConversations,
            #format: format,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> saveExportToFile(Map<String, dynamic>? exportData) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveExportToFile,
          [exportData],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #saveExportToFile,
            [exportData],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getBackupHistory({int? limit = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackupHistory,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> restoreFromBackup(String? backupId) => (super.noSuchMethod(
        Invocation.method(
          #restoreFromBackup,
          [backupId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanupExpiredBackups() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredBackups,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getStorageUsage() => (super.noSuchMethod(
        Invocation.method(
          #getStorageUsage,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [DisasterRecoveryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDisasterRecoveryService extends _i1.Mock
    implements _i6.DisasterRecoveryService {
  MockDisasterRecoveryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> createRecoveryPlan({
    required String? planName,
    required List<String>? criticalDataTypes,
    required Map<String, dynamic>? recoveryConfig,
    int? backupFrequencyHours = 24,
    int? retentionDays = 30,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createRecoveryPlan,
          [],
          {
            #planName: planName,
            #criticalDataTypes: criticalDataTypes,
            #recoveryConfig: recoveryConfig,
            #backupFrequencyHours: backupFrequencyHours,
            #retentionDays: retentionDays,
          },
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #createRecoveryPlan,
            [],
            {
              #planName: planName,
              #criticalDataTypes: criticalDataTypes,
              #recoveryConfig: recoveryConfig,
              #backupFrequencyHours: backupFrequencyHours,
              #retentionDays: retentionDays,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> executeDisasterRecovery({
    required String? recoveryPlanId,
    String? targetEnvironment,
    bool? validateIntegrity = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeDisasterRecovery,
          [],
          {
            #recoveryPlanId: recoveryPlanId,
            #targetEnvironment: targetEnvironment,
            #validateIntegrity: validateIntegrity,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> migrateData({
    required String? sourceSystem,
    required String? targetSystem,
    required List<String>? dataTypes,
    required Map<String, dynamic>? migrationConfig,
    bool? preserveOriginal = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #migrateData,
          [],
          {
            #sourceSystem: sourceSystem,
            #targetSystem: targetSystem,
            #dataTypes: dataTypes,
            #migrationConfig: migrationConfig,
            #preserveOriginal: preserveOriginal,
          },
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #migrateData,
            [],
            {
              #sourceSystem: sourceSystem,
              #targetSystem: targetSystem,
              #dataTypes: dataTypes,
              #migrationConfig: migrationConfig,
              #preserveOriginal: preserveOriginal,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> checkSystemHealth() => (super.noSuchMethod(
        Invocation.method(
          #checkSystemHealth,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>?> getRecoveryJobStatus(String? jobId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecoveryJobStatus,
          [jobId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>?> getMigrationJobStatus(String? jobId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMigrationJobStatus,
          [jobId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>> testRecoveryProcedures(
          String? recoveryPlanId) =>
      (super.noSuchMethod(
        Invocation.method(
          #testRecoveryProcedures,
          [recoveryPlanId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}

/// A class which mocks [MessageRetentionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRetentionService extends _i1.Mock
    implements _i7.MessageRetentionService {
  MockMessageRetentionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> setRetentionPolicy({
    required String? entityId,
    required String? entityType,
    required Map<String, int>? retentionPeriods,
    bool? autoCleanup = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setRetentionPolicy,
          [],
          {
            #entityId: entityId,
            #entityType: entityType,
            #retentionPeriods: retentionPeriods,
            #autoCleanup: autoCleanup,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getRetentionPolicy(String? entityId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRetentionPolicy,
          [entityId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> cleanupExpiredMessages(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredMessages,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanupExpiredMessagesForAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredMessagesForAllUsers,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cleanupExpiredGroupMessages(String? groupId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cleanupExpiredGroupMessages,
          [groupId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getCleanupStatistics(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCleanupStatistics,
          [userId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> scheduleAutomaticCleanup({
    String? userId = 'global',
    Duration? interval = const Duration(days: 7),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleAutomaticCleanup,
          [],
          {
            #userId: userId,
            #interval: interval,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [DataMigrationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataMigrationService extends _i1.Mock
    implements _i8.DataMigrationService {
  MockDataMigrationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> createMigrationConfig({
    required String? configName,
    required String? sourceType,
    required String? targetType,
    required Map<String, dynamic>? sourceConfig,
    required Map<String, dynamic>? targetConfig,
    required List<String>? dataTypes,
    Map<String, dynamic>? transformationRules,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMigrationConfig,
          [],
          {
            #configName: configName,
            #sourceType: sourceType,
            #targetType: targetType,
            #sourceConfig: sourceConfig,
            #targetConfig: targetConfig,
            #dataTypes: dataTypes,
            #transformationRules: transformationRules,
          },
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #createMigrationConfig,
            [],
            {
              #configName: configName,
              #sourceType: sourceType,
              #targetType: targetType,
              #sourceConfig: sourceConfig,
              #targetConfig: targetConfig,
              #dataTypes: dataTypes,
              #transformationRules: transformationRules,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> executeMigration({
    required String? configId,
    bool? dryRun = false,
    bool? preserveSource = true,
    Map<String, dynamic>? overrides,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeMigration,
          [],
          {
            #configId: configId,
            #dryRun: dryRun,
            #preserveSource: preserveSource,
            #overrides: overrides,
          },
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #executeMigration,
            [],
            {
              #configId: configId,
              #dryRun: dryRun,
              #preserveSource: preserveSource,
              #overrides: overrides,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> migrateFirestoreToSQLite({
    required List<String>? collections,
    required String? sqliteDbPath,
    bool? preserveFirestore = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #migrateFirestoreToSQLite,
          [],
          {
            #collections: collections,
            #sqliteDbPath: sqliteDbPath,
            #preserveFirestore: preserveFirestore,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> migrateSQLiteToFirestore({
    required String? sqliteDbPath,
    required List<String>? tables,
    bool? preserveSQLite = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #migrateSQLiteToFirestore,
          [],
          {
            #sqliteDbPath: sqliteDbPath,
            #tables: tables,
            #preserveSQLite: preserveSQLite,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<String> exportToJSON({
    required List<String>? dataTypes,
    String? filePath,
    bool? includeMetadata = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportToJSON,
          [],
          {
            #dataTypes: dataTypes,
            #filePath: filePath,
            #includeMetadata: includeMetadata,
          },
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #exportToJSON,
            [],
            {
              #dataTypes: dataTypes,
              #filePath: filePath,
              #includeMetadata: includeMetadata,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> importFromJSON({
    required String? filePath,
    bool? validateData = true,
    bool? overwriteExisting = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importFromJSON,
          [],
          {
            #filePath: filePath,
            #validateData: validateData,
            #overwriteExisting: overwriteExisting,
          },
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>?> getMigrationJobStatus(String? jobId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMigrationJobStatus,
          [jobId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getMigrationHistory(
          {int? limit = 20}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMigrationHistory,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [BackupSchedulerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupSchedulerService extends _i1.Mock
    implements _i9.BackupSchedulerService {
  MockBackupSchedulerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> createBackupSchedule({
    required String? scheduleName,
    required Duration? interval,
    required List<String>? dataTypes,
    required Map<String, dynamic>? backupConfig,
    bool? isActive = true,
    DateTime? startTime,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBackupSchedule,
          [],
          {
            #scheduleName: scheduleName,
            #interval: interval,
            #dataTypes: dataTypes,
            #backupConfig: backupConfig,
            #isActive: isActive,
            #startTime: startTime,
          },
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #createBackupSchedule,
            [],
            {
              #scheduleName: scheduleName,
              #interval: interval,
              #dataTypes: dataTypes,
              #backupConfig: backupConfig,
              #isActive: isActive,
              #startTime: startTime,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateBackupSchedule({
    required String? scheduleId,
    String? scheduleName,
    Duration? interval,
    List<String>? dataTypes,
    Map<String, dynamic>? backupConfig,
    bool? isActive,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBackupSchedule,
          [],
          {
            #scheduleId: scheduleId,
            #scheduleName: scheduleName,
            #interval: interval,
            #dataTypes: dataTypes,
            #backupConfig: backupConfig,
            #isActive: isActive,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBackupSchedule(String? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBackupSchedule,
          [scheduleId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getBackupSchedules() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackupSchedules,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  void startScheduler() => super.noSuchMethod(
        Invocation.method(
          #startScheduler,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopScheduler() => super.noSuchMethod(
        Invocation.method(
          #stopScheduler,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<String> executeBackupNow(String? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeBackupNow,
          [scheduleId],
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #executeBackupNow,
            [scheduleId],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<Map<String, dynamic>> getScheduleStatistics(String? scheduleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScheduleStatistics,
          [scheduleId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> createDefaultSchedules(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDefaultSchedules,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getGlobalBackupStatistics() =>
      (super.noSuchMethod(
        Invocation.method(
          #getGlobalBackupStatistics,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
