// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkqk0UpmgGCabHRSQK3V9oH7Dxb5sa9Vk',
    appId: '1:132354679195:web:bb87ce4dde748e8083013e',
    messagingSenderId: '132354679195',
    projectId: 'talowa',
    authDomain: 'talowa.firebaseapp.com',
    storageBucket: 'talowa.firebasestorage.app',
    measurementId: 'G-4L640E27ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEZwrO7edBTlfbGtKyH9Z0M7DcXthDZ6Q',
    appId: '1:132354679195:android:0d857b6e7f33760683013e',
    messagingSenderId: '132354679195',
    projectId: 'talowa',
    storageBucket: 'talowa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPqk3p25GH0RJI_VGo5MUCq9QGibQbuM',
    appId: '1:132354679195:ios:88abaa5b815f955883013e',
    messagingSenderId: '132354679195',
    projectId: 'talowa',
    storageBucket: 'talowa.firebasestorage.app',
    iosBundleId: 'com.example.talowa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuPqk3p25GH0RJI_VGo5MUCq9QGibQbuM',
    appId: '1:132354679195:ios:88abaa5b815f955883013e',
    messagingSenderId: '132354679195',
    projectId: 'talowa',
    storageBucket: 'talowa.firebasestorage.app',
    iosBundleId: 'com.example.talowa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkqk0UpmgGCabHRSQK3V9oH7Dxb5sa9Vk',
    appId: '1:132354679195:web:89037424c20b677483013e',
    messagingSenderId: '132354679195',
    projectId: 'talowa',
    authDomain: 'talowa.firebaseapp.com',
    storageBucket: 'talowa.firebasestorage.app',
    measurementId: 'G-VWSTHMXX82',
  );

}
